# Generated by Django 3.2.16 on 2023-03-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('activation_time', models.IntegerField(default=0, verbose_name='激活日期')),
                ('limit_time', models.IntegerField(default=0, verbose_name='使用期限')),
                ('license_state', models.IntegerField(default=2, verbose_name='使用状态')),
            ],
            options={
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('mid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='商家ID')),
                ('name', models.CharField(default='', max_length=64, unique=True, verbose_name='商家名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('address', models.CharField(default='', max_length=64, verbose_name='地址')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('approval', models.BooleanField(default=False, verbose_name='审批通过')),
                ('reason', models.CharField(default='', max_length=64, verbose_name='审批原因')),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='身份证')),
                ('phone', models.CharField(max_length=64, verbose_name='手机号')),
                ('user_name', models.CharField(max_length=64, verbose_name='姓名')),
            ],
            options={
                'db_table': 'registrant',
            },
        ),
        migrations.CreateModel(
            name='MerchantRegistrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='商家ID')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.registrant', verbose_name='注册人ID')),
            ],
            options={
                'db_table': 'merchant_registrant',
            },
        ),
        migrations.CreateModel(
            name='MerchantLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.license', verbose_name='许可码ID')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant', verbose_name='商家ID')),
            ],
            options={
                'db_table': 'merchant_license',
            },
        ),
    ]
