"""
Django settings for wendy project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os

from pathlib import Path
from django.core.cache.backends.locmem import LocMemCache

cache = LocMemCache("wendy", {})

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_6)5=of^s90r_6h+3+e98r8d*7q$ygt^q8+#mgba&lit86uuw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['64.176.201.182', '0.0.0.0', '*', 'wendy-mysql-container']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'advertise',
    'cart',
    'login',
    'merchant',
    'order',
    'photo',
    'stock',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.permission.AuthPermissionRequired',
]

CORS_ORIGIN_ALLOW_ALL = True        # 允许所有域名跨域(优先选择)

CORS_ALLOW_CREDENTIALS = True       # 允许携带cookie

ROOT_URLCONF = 'wendy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wendy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wendy_django_db',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'wendy-mysql-container',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 腾讯云（短信服务）
TX_SECRET_ID = 'AKIDNZgcLtJWWKPI2e9ayGD7uaL1c1FvSn6H'   # api密钥id
TX_SECRET_KEY = 'A96uZ3eDfw0sywlMm2GLEyWqy1sfQF3n'      # api密钥密码
SING_NAME = '娜娜起名困难症公众号'                        # 签名
SMS_SDK_ID = '1400789234'                               # 签名ID
TEMPLATE_ID = '1665653'                                 # 模板ID
TIME_LIMIT = '15'                                       # 时间限制

# 系统语言
LANGUAGE = 'cn'

# 微信小程序（登录验证）
APP_ID = 'wx21322a0aa4d64815'
APP_Secret = '7cc27b214120cebd73d092c194796b99'

