# Generated by Django 3.2.16 on 2023-03-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('openid', models.CharField(max_length=64, verbose_name='下单用户')),
                ('state', models.IntegerField(verbose_name='订单状态')),
                ('finish_time', models.IntegerField(default=0, verbose_name='完成订单时间')),
                ('book_time', models.IntegerField(default=0, verbose_name='预约取件时间')),
                ('user_name', models.CharField(max_length=64, verbose_name='收货人名字')),
                ('phone', models.CharField(max_length=64, verbose_name='手机号')),
                ('way', models.CharField(max_length=64, verbose_name='收货方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
        migrations.CreateModel(
            name='OrderStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('pay', models.FloatField(verbose_name='付款金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='订单ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='订单购买内容')),
            ],
            options={
                'db_table': 'order_stock',
            },
        ),
    ]
