# Generated by Django 3.2.16 on 2023-03-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('aid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='广告ID')),
                ('contract', models.CharField(max_length=64, unique=True, verbose_name='合同编号')),
                ('source', models.CharField(default='', max_length=64, verbose_name='广告来源')),
                ('illustrate', models.CharField(default='', max_length=64, verbose_name='广告说明')),
                ('principal', models.CharField(default='', max_length=64, verbose_name='负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'advertise',
            },
        ),
    ]
