# Generated by Django 3.2.16 on 2023-03-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAdvertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('req_time', models.IntegerField(verbose_name='点击广告时间')),
                ('aid', models.CharField(max_length=64, verbose_name='广告ID')),
            ],
            options={
                'db_table': 'request_ad',
            },
        ),
        migrations.CreateModel(
            name='RequestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('req_time', models.IntegerField(verbose_name='访问时间')),
            ],
            options={
                'db_table': 'request_user',
            },
        ),
    ]
